#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Set-IntSpan
version:      1.08
version_from: IntSpan.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
